s = "qwe rty uio"
print("Str. before upper is =", s)
spase_1 = s.find(" ")
space_2 = s.find (" ", spase_1+1)
mid_of_s = s[ spase_1 +1:space_2]
left_of_s = s[:spase_1]
right_of_s = s[space_2 + 1:]
result = left_of_s + " " + mid_of_s.upper() + " " + right_of_s
print("Str. after upper=", result)